# Aufgabe 2 - Laden und Speichern von Daten

<p style="border-left:5px solid red;padding:0.6em;box-sizing:border-box;">
<strong>Lernziele:</strong><br/>
    Diese Übung führt sie an den Umgang mit den externen Dateien heran. Dies ist insbesondere wichtig, da Messdaten häufig als externes Dokument vorliegen und importiert werden müssen bevor sie ausgewertet werden können.
</p>

<p style="border-left:5px solid blue;padding:0.6em;box-sizing:border-box;">
<strong>Wichtigste Funktionen für diese Übung:</strong><br/>
    Dies sind die wichtigsten Funktionen die sie während dieser Übung benötigen:<br>
    Die jeweilige Syntax beschreibt eine examplarische Verwendung. Im allgemeinen haben die Funktionen weitere Argumente die übergeben werden können. Der Funktionsname ist jeweils ein Link zur offiziellen Dokumentation, welche alle Argumente darlegt und ihre Funktion beschreibt. <br>
    <a href="https://docs.python.org/3/library/os.html#os.getcwd">os.getcwd()</a> Gibt das aktuelle Verzeichnis aus.<br>
    <a href="https://docs.python.org/3/library/os.html#os.listdir">os.listdir(path)</a> Gibt alle Inhalte des Ordners am Pfad <em>path</em> aus.<br>
    <a href="https://docs.python.org/3/library/os.path.html#os.path.join">os.path.join(path1, path2)</a> Verbindet die Strings von mehreren Pfaden/Dateien zu einem einzelnen Pfad zu der gewünschten Datei.<br>
    <a href="https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html">data = numpy.loadtxt(filepath, <em>optional arguments</em>)</a> Lädt die Daten in einem Dokument und schreibt die Daten in eine Variable <em>data</em><br>
    <a href="https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html">numpy.savetxt(filename, data)</a> Schreibt das Array <em>data</em> in eine neu Data mit dem Namen <em>filename</em>.<br>
    
</p>

## **Hintergrund**
Im allgemeinen wollen wir Daten analysieren, die mit einem Computerprogramm oder mit einem Messgerät aufgenommen worden sind und die in einer Datei vorliegen. In diesen Dateien können die Daten in verschiedenen Formen gespeichert sein. Wir beschränken uns hier ausschliesslich auf Textdateien, in denen die Daten im ASCII-Format vorliegen.
Den Inhalt dieser Dateien wollen wir in Python laden und einer Variable (z.B. einem Array) zuweisen. Nach der Analyse wollen wir diese Daten wiederum in einer neuen Datei abspeichern. 

Der Inhalt einer Messdaten-Datei besteht üblicherweise aus einem Header mit Metadaten und den Messdaten selbst. Der Header ist dazu da, die Messung zu beschreiben, so dass man später nachvollziehen kann, zu welchem Experiment die Daten gehören. Ausserdem enthält er normalerweise eine Erklärung zur Struktur der Daten, z.B. was die einzelnen Zeilen und Spalten bedeuten.

Wir haben Ihnen mit der Übung die Beispieldatei "example_data.txt" zur Verfügung gestellt. Wenn Sie diese in einem Texteditor öffnen, können Sie sich ein Bild davon machen, wie eine Messdaten-Datei aussehen könnte. Für die Aufgaben unten werden Sie selbst eine neue Datei erstellen und von Hand Zahlen eingeben, damit Sie an einem einfachen Beispiel ausprobieren können, wie Python und Sie selbst mit der Datei interagieren können.

Die Datei mit den Messdaten ist auf dem Computer gespeichert und zwar in einer Datei mit einem Namen und einer Endung, die üblicherweise das Dateiformat charakterisiert: "Name.Endung"
Beispiele für Dateiendungen sind: 

|Dateiendung | Beschreibung |
| :- | :- |
|.txt | Textdatei |
| .html | Eine Textdatei, die einen HTML-Code enthält und von einem Browser interpretiert werden kann |
| .py | Eine Textdatei, die ein Python-Skript enthält das von einem Python-Interpreter interpretiert werden kann |
| .ipynb | Eine IPython Notebook-Datei, die in JSON gespeichert ist |
|.jpg | Eine Binärdatei, die ein Bild im JPEG-Format enthält |

Diese Dateien sind im Computer in einer Verzeichnisstruktur organisiert. In Windows sieht so ein Verzeichnisbaum üblicherweise so aus:

| Verzeichnis | Beschreibung |
| :- | :- |
| C:\ | Root-Verzeichnis (Wurzel des Baums). |
| C:\Progam Files\ | Hier sind alle 64bit Programme abgespeichert die auf dem Computer installiert sind. |
| C:\Program Files (x86)\ | Hier sind alle 32bit Programme abgespeichert die auf dem Computer installiert sind. |
| C:\Users\ | Hier sind (üblicherweise) die Dateien abgespeichert, die von den Computerbenutzern angelegt oder erzeugt wurden. |
| C:\Users\Name | Im Users-Ordner ist für jeden Benutzer (jeden Account) ein Ordner mit dem Namen (Name) des Accounts angelegt. |
| C:\Users\Name\Desktop | Hier sind alle Dateien abgespeichert, die auf dem Desktop dieser Benutzerin liegen. |
| C:\Users\Name\Documents | Hier sind üblicherweise die Dateien abgespeichert, die der Benutzer mit Programmen erstellt hat. |
| C:\Users\Name\Downloads | Hier sind üblicherweise die Dateien abgespeichert, die die Benutzerin aus dem Internet heruntergeladen hat. |
| C:\Users\Name\OneDrive | Hier sind alle Dateien lokal gespeichert, die aus dem OneDrive Cloud-Speicher synchronisiert werden. |


**MacOS**:

- Das Root-Verzeichnis ist "/"
- Die Programme sind in "/Applications/"
- Die User-Ordner und eine analoge Substruktur wie in Windows sind in "/Users/Name"

**Linux**:

- Das Rootverzeichnis ist "/"
- Systemprogramme sind in "/bin/", "/sbin/", "/usr/bin", "/usr/sbin/"
- Die Systemkonfiguration ist in "/etc/"
- Die Userordner und analoge Substruktur sind in "/home/name/"

Achtung! Auf Windows sind Pfad- und Dateinamen standardmässig case-insensitive (d.h. Gross- und Kleinschreibung sind irrelevant), während auf MacOS und Linux die Pfad- und Dateinamen case-sensitive sind.

## **Aufgaben**

### Orientierung in der Verzeichnisstruktur

Das IPython Notebook ist auch eine Datei, die irgendwo in diesem Verzeichnisbaum liegt, z.B.
C:\Users\Name\Documents\Code\Python

Wenn wir Jupyter notebook starten, starten wir im Browser mit einem Dateiexplorer, der es uns erlaubt zu dem Verzeichnis zu wechseln, in dem wir unseren Code abgespeichert haben bzw. in dem wir unseren Code abspeichern wollen.

Ordnung in dieser Verzeichnisstruktur zu halten ist hilfreich.

In Python ist dann standardmässig das Arbeitsverzeichnis dasjenige Verzeichnis, in dem die Programmdatei, also der Code, liegt. Das Arbeitsverzeichnis heisst auch "current working directory" und kann folgendermassen ermittelt werden:

In [1]:
# Einbinden der Bibliothek für Zugriff auf die Dateistruktur
import os
# Ermitteln des current working directory und sofortige Ausgabe
print(os.getcwd())

/home/flopsi/Documents/Programming/Datenanalyse/Serien/01


Aufgaben:

- Kopieren Sie den soeben ermittelten Pfad zum Arbeitsverzeichnis in die Zwischenablage.
- Öffnen Sie den Dateiexplorer Ihres Betriebssystems
- Fügen Sie den kopierten Pfad in die Pfadzeile des Explorers und bestätigen Sie die Änderung

Mac: Gehe zu... -> Gehe zum Ordner -> *Pfad hierher kopieren* (shortcut: Cmd-Shift-G)<br>
Linux: Kommt auf den verwendenten file explorer an. Oft kann man mit Ctrl-L die Pfadzeile auswählen.


Nun haben Sie ein offenes Explorer-Fenster zum Arbeitsverzeichnis!

Hier sehen wir alle Dateien und Ordner in diesem Verzeichnis. Wir können das auch in Python anzeigen:

In [2]:
# Für mehr Übersichtlichkeit benutzen wir eine Variable 'cwd' um den Pfad des Arbeitsverzeichnisses zu speichern
cwd = os.getcwd()
# Erzeugen einer Liste 'files' mit allen Dateien und Ordnern im cwd
files = os.listdir(cwd)
# Ausgabe der Liste
print(files)

['Aufgabe 1 - Arrays.ipynb', 'example_data.txt', 'Skillcheck.txt', 'Aufgabe 2 - Laden und Speichern von Daten.ipynb']


Dieser Code Erzeugt eine Liste mit allen Ordnern und Verzeichnissen im Arbeitsverzeichnis und gibt diese aus.

Aufgaben:
- Erzeugen Sie eine Textdatei mit dem Namen "Data.txt" im Arbeitsverzeichnis (z.B. in Windows: Rechtklick im Dateiexplorer, im Kontextmenü: New - Text Document; Mac: Öffnen Sie Textedit und erzeugen sie die Datei und speichern Sie diese in dem Ordner, den Sie als Arbeitsverzeichnis identifiziert haben)
- Öffnen Sie diese Datei mit einem Texteditor (z.B. in Windows: Rechtsklick auf die Datei, im Kontextmenü: Open with - Notepad)
- Geben Sie im Editor jeweils eine Zahl in ein paar Zeilen ein.
- Speichern Sie die Datei
- Führen Sie den obigen Code erneut aus. Sie sollten nun die neue Datei "Data.txt" in der Liste wiederfinden können.

Um im allgemeinen auf eine Datei zugreifen zu können müssen wir nicht nur ihren Namen, sondern auch ihre Position im Verzeichnisbaum kennen. Also erzeugen wir uns einen absoluten Pfad, der den Zugriff auf die Datei vollständig charakterisiert:

In [3]:
file = os.path.join(cwd, 'Data.txt')
print(file)

/home/flopsi/Documents/Programming/Datenanalyse/Serien/01/Data.txt


Nun Sehen Sie den absoluten Pfad der Datei (in Windows üblicherweise beginnend mit "C:\"), mit dem Dateinamen am Ende.

### Laden von Dateien

Nun können wir den Inhalt der Datei in Python laden:

In [4]:
import numpy as np
# Laden der Datei die über den Pfad 'file' charakterisiert ist und abspeichern der Dateiinhalte in der Variable 'data'
data = np.loadtxt(file)
print(data)

[ 1.  4.  9. 16. 25.]


Nun sehen sie die Zahlen, die sie zuvor in die Datei geschrieben haben.

Nebenbemerkung: Dateien können auch über relative Pfade, ausgehend vom aktuellen Arbeitsverzeichnis, angegeben werden. Das heisst wir können diese Daten also auch einfach mit: `data = np.loadtxt('Data.txt')` laden, da sie sich im gleichen Verzeichnis wie unser IPython-Notebook befinden. Probieren Sie es aus.

Aufgabe:
- Öffnen Sie wieder die Datei "Data.txt" in einem Editor und geben sie nun Zahlen in zwei Zeilen ein und speichern Sie die Datei. Wichtig: Die Zahlen müssen durch Leerzeichen getrennt sein und in beiden Zeilen müssen gleich viele Zahlen stehen!
- Führen Sie den vorherigen Code wieder aus. Diese Funktion ist recht intelligent und interpretiert das Format der Zahlen oft vernünftig.

In [5]:
data = np.loadtxt(file)
print(data)

[[ 1.  1.]
 [ 4.  2.]
 [ 9.  3.]
 [16.  4.]
 [25.  5.]]


Bisher enthält die Datei nur Zahlen, üblicherweise wollen wir in den ersten paar Zeilen aber auch Metadaten speichern. Metadaten könnten zum Beispiel sein: Das Datum der Messung, der Name des Messgeräts, das die Dateien erzeugt hat, oder die Bezeichnung der Messgrössen, die in der Datei gespeichert sind. Solche Metadaten sind wichtig, damit man später noch nachvollziehen kann, was gemessen wurde und wie.

Aufgabe:

- Öffnen Sie nochmal die Datei in einem Editor und fügen Sie am Anfang eine oder mehrere Zeilen mit Metadaten ein, z.B. ihrem Namen, dem heutigen Datum, etc.

Da die Zeilen mit den Metadaten nicht strukturiert sind, kann die funktion np.loadtxt sie nicht interpretieren: Wenn sie den obigen Code nochmal ausführen, sollten Sie eine Fehlermeldung erhalten. Daher wollen wir der Funktion die Anweisung mitgeben, die Zeilen mit den Metadaten zu überspringen. Das entsprechende Argument finden Sie im der Dokumentation der np.loadtxt Funktion:

In [6]:
np.loadtxt?

Signature:
np.loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
    *,
    quotechar=None,
    like=None,
)
Docstring:
Load data from a text file.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return bytes or strings. The strings
    in a list or produced by a generator are treated as lines.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or

Aufgabe:

- Finden Sie in der Dokumentation das Argument, mit dem Sie festlegen können, wie viele Zeilen am Anfang der Datei übersprungen werden und wenden Sie es an, um Ihre Datei einzulesen.

In [7]:
data = np.loadtxt(file, skiprows=2)
print(data)

[[ 1.  1.]
 [ 4.  2.]
 [ 9.  3.]
 [16.  4.]
 [25.  5.]]


Wenn man nicht von vornherein weiss, wie viele Zeilen Metadaten die Datei enthält, ist es oft am einfachsten die Datei in einem Texteditor zu öffnen und die Zeilen zu zählen. Falls die Zeilen mit den Metadaten alle mit dem gleichen Symbol beginnen (z.B. "#"), können diese auch automatisch ignoriert werden, indem man das Argument `comments='#'` verwendet.

Aufgabe:

- Nun haben Sie alle Mittel, die Sie brauchen, um die Daten aus der Beispieldatei "example_data.txt" einzulesen. Versuchen Sie es!

In [11]:
data = np.loadtxt('example_data.txt', comments='%')
print(data)

[[ 0.00000000e+00  7.27941176e+00  2.20957359e+08 -5.98748177e-21]
 [ 1.91035016e-01  7.38970588e+00  2.20957333e+08 -5.98748177e-21]
 [ 0.00000000e+00  7.50000000e+00  2.22048844e+08 -6.05622763e-21]
 ...
 [ 6.49519053e+00 -3.52941176e+00  2.20957324e+08 -5.98748177e-21]
 [ 6.30415551e+00 -3.63970588e+00  2.20957338e+08 -5.98748177e-21]
 [ 6.49519053e+00 -3.75000000e+00  2.22048844e+08 -6.05622763e-21]]


Weiter unten in diesem Notebook gibt es noch Beispiele mit Erklärungen zu etwas allgemeineren Möglichkeiten Daten einzulesen. Dies kann nützlich sein, wenn man nicht genau weiss, wie die Daten Strukturiert sind, oder einen Code schreibt, der verschiedene Arten von Daten lesen soll. Für diesen Kurs wird die Funktion np.loadtxt jedoch ausreichen.

### Daten abspeichern

Nun wollen wir die Daten wieder abspeichern um sie zu archivieren oder sie gegebenenfalls zu einem späteren Zeitpunkt weiter zu analysieren.

Hierzu gibt es verschiedene Möglichkeiten:

1) Die einfachste Möglichkeit ist wieder die Numpy-Funktion savetxt, das Äquivalent zu loadtxt:


In [12]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
z = np.array([-5, -6, -7, -8, -9])

np.savetxt('DataOut.txt', (x,y,z), delimiter=',')

Die wichtigsten Parameter sind hier:
- 'DataOut.txt': Der Dateiname der Ausgabedatei. Hier könnte auch wieder ein absoluter Pfad angegeben werden. In dieser einfachen Form mit einem Dateinamen wird die Datei im aktuellen Arbeitsverzeichnis erstellt.
- (x,y,z): Die Daten, die wir abspeichern wollen. Hier übergeben wir die drei Arrays, die Zeilenweise abgespeichert werden.
- delimiter=',': Der Delimiter, also das Zeichen, mit dem die einzelnen Datenwerte in der Datei voneinander getrennt werden.

Aufgabe:
- Öffnen Sie sie Datei die sie so erstellt haben. Was ist anders als in der Datei, die wir eingelesen haben?
- Überlegen Sie sich, wie wir vorgehen könnten um die Daten in dem gleichen Format abzuspeichern wie in der Datei die wir eingelesen haben.

Um Metadaten einzufügen, kann man einen String für das Argument `header` übergeben.

In [13]:
np.savetxt('DataOut.txt', (x,y,z), delimiter=',', header='Beispieldatei Datenanalyse, 14.2.2023. Format: x, y, z')

### Format Strings: Zahlenwerte für die Ausgabe formatieren

Berechnete Zahlenwerte, die ausgegeben werden, müssen oft formatiert werden, z.B. um eine sinnvolle Anzahl signifikanter Ziffern anzugeben. Ausserdem möchte man häufig einen beschreibenden Text damit kombinieren. Beides wird mit format strings erreicht.

Hierzu werden in einem String Platzhalter eingefügt, und die Werte, die die Platzhalter ersetzen sollen, mit der `format` Funktion an den String weitergegeben.

In [14]:
print('Die Summe der Zahlen {} und {} ist gleich {}.'.format(3, 5, 8))

Die Summe der Zahlen 3 und 5 ist gleich 8.


Die geschweiften Klammern sind die Platzhalter für die Werte der Argumente der format-Funktion.

In den Platzhaltern kann man Formatierungsanweisungen einfügen, die angeben wie die Zahlen interpretiert und formatiert werden sollen:
- `{:d}` : Integer
- `{:f}` : Fliesskomma
- `{:0.2f}`: Fliesskomma mit 2 Nachkommastellen

In [20]:
print('{:.2f}'.format(1.3502))

1.35


Aufgabe:

- Probieren Sie verschieden Formate aus. Erzeugen Sie zum Beispiel mit einer Funktion wie np.exp Gleitkommazahlen und geben Sie diese mit einer fixen Anzahl Ziffern aus.

In [21]:
print('{:.4f}'.format(np.exp(1.23)))

3.4212


Solche Formatierungsanweisungen können auch in der np.savetxt Funktion verwendet werden, um die Darstellung der Zahlen zu bestimmen.

## Zusammenfassung

Mit diesen einfachen Beispielen können Sie nun Daten aus Textdateien einlesen und weiterverarbeiten. Darüber hinaus können Sie Daten in Textdateien abspeichern und Zahlenwerte in formatierte Strings umwandeln.


## Zusatz: Manuelles Einlesen von Dateien

Sie haben in den Übungen die Funktion np.loadtxt schon ein bisschen kennen gelernt und damit gearbeitet. Wir wollen nun ein bisschen allgemeiner auf Daten in Textdateien blicken.

Oft liegen die Daten aber in einem speziellen Format vor (z.B. vorgegeben von dem Messgerät das die Datei erzeugt hat) und wir wollen sie auch entsprechend einlesen.
Um zu verstehen wie die Daten in einer Datei vorliegen können wir die Datei mit einem Editor öffnen und betrachten. Wir können aber auch in Python eine Datei etwas allgemeiner verstehen:

Um alle Zeilen einer Textdatei einzulesen und in einer Liste aus Strings zu speichern ist folgender Code praktisch:

In [27]:
with open('Data.txt', 'r') as f:
    lines = f.readlines()

Mit dem open-Befehl öffnen wir die Datei (hier die Datei mit dem Pfad 'file'). Um die Datei nur zu lesen, übergeben wir das Argument 'r' (um die Datei zu schreiben würden wir 'w' übergeben). Die Variable 'f' ist ein Datei-Objekt auf dem wir Methoden wie z.B. hier readlines() anwenden können. Die Methode readlines() übergibt eine Liste aus Strings die alle Zeilen der Datei beinhaltet.
Die 'with' Umgebung garantiert, dass die Datei am Ende (auch im Misserfolg) wieder ordentlich geschlossen wird.

Wir können diese Zeilen ausgeben:

In [28]:
print(lines)

['x, y\n', '0.1, 0.31\n', '0.2, 0.45\n', '0.3, 0.55\n']



Die Variable lines ist eine Liste in der jedes Element eine Zeile als String beinhaltet. Um auf eine einzelne Zeile bzw. ein Element in dieser Liste zugreifen zu können, indexieren wir dieses Element:

In [29]:
print(lines[1])

0.1, 0.31



Dies gibt uns das zweite Element aus der Liste 'lines' aus. Falls Sie mehr als eine Zeile Metadaten in die Datei eingegeben haben, müssen Sie den Index anpassen, um die erste Zeile mit Daten zu erhalten.

Um mit den Daten arbeiten zu können, müssen wir sie aus dem String extrahieren und in ein Zahlenformat umwandeln. Das können wir z.B. mit dem Numpy-Befehl np.fromstring() machen:

In [32]:
a = np.fromstring(lines[1], dtype=float, sep=',')

Hier übergeben wir als Argumente:
- lines[1]: Die zweite Zeile aus der Datei
- dtype=float: Hiermit spezifizieren wie wir die Zahlen interpretiert werden sollen. In diesem Fall als Fliesskommazahl (Floating point, kurz float). Für Integer könnten wir int übergeben.
- sep=' ': Hiermit spezifizieren wir wodurch die einzelnen Zahlen in dem String separiert werden. Der sogenannte Delimiter. Hier ist das ein Leerzeichen. Oft werden in Dateien die einzelnen Werte mit einem Komma separiert, dann würde man sep=',' als Delimiter übergeben.

Das Ergebnis ist ein Array 'a' aus float Zahlen.

Mit

In [33]:
print(a)

[0.1  0.31]


können wir wiederum das Array ausgeben.

Idealerweise beinhalten Daten-Dateien nicht nur die Daten (also Zahlen), sondern auch Metainformation über die Daten bzw. das Experiment durch das sie zustande gekommen sind. Ein einfaches Beispiel wäre eine Datei mit folgendem Inhalt:

x, y<br>
0.1, 0.31<br>
0.2, 0.45<br>
0.3, 0.55<br>

Hier sind offensichtlich die Werte für x und y genmessen worden. 

Aufgabe:
- Kopieren sie diesen Textblock in Ihre Data.txt Datei, oder erzeugen Sie einen ähnlichen Inhalt, und speichern Sie die Datei ab.
- Öffnen Sie die Datei in Python und laden Sie alle Zeilen in eine Liste aus Strings.
- Geben Sie diese Liste aus Strings aus.

Wenn wir nun die Daten aus der Liste aus Strings extrahieren wollen, müssen wir die erste Zeile ignorieren, weil diese keine Zahlenwerte enthält.
Wir müssen also alle, bis auf die erste Zeile in ein Daten-Array umwandeln. Dazu verwenden wir hier eine Schleife:

In [34]:
for l in lines:
    print(l)

x, y

0.1, 0.31

0.2, 0.45

0.3, 0.55



Diese einfache Schleife wird für jedes Element in lines durchgeführt. Um nun das erste Element zu überspringen schreiben wir:

In [35]:
for l in lines[1:]:
    print(l)

0.1, 0.31

0.2, 0.45

0.3, 0.55



In den eckigen Klammern wird der Index bzw ein Bereich einer Liste oder eines Arrays indiziert.


Um nun die Daten in ein Array einzulesen können wir wie folgt vorgehen:

In [36]:
i = 0
for l in lines[1:]:
    if (i==0):
        d = np.array([np.fromstring(l, dtype=float, sep=',')])
    else:
        d = np.append(d, np.array([np.fromstring(l, dtype=float, sep=',')]), axis=0)
    i = i+1

Dies ist ein Beispiel für den Fall, dass wir nicht viel Über die Daten in der Datei wissen. Insbesondere wissen wir nicht wie viele Zeilen die Datei hat und auch nicht wie viele Einträge pro Zeile. Wir iterieren durch alle Zeilen ausser der ersten (die ja keine Daten enthält) und für die erste Zeile (i==0) merken wir uns den Array, der aus der Zeile erzeugt wurde.
Für alle weiteren Zeilen (i>0) hängen wir die neuen Daten an den Datenarray an. Auf diese Weise erhalten wir einen 2-Dimensionalen Array, in dem gleichen Format wie die Daten in der Datei. Das wird garantiert in dem wir die neue Zeile entlang der Achse 0 an den alten Array anhängen. Was passiert wenn wir stattdessen Achse 1 angeben?
Das ist sicher nicht das optimale Vorgehen bei Arrays, ist aber recht einfach.

Alternative können wir durch Inspektion der Datei mehr über das Datenformat lernen und etwas anders vorgehen:

In [38]:
d = np.zeros((len(lines)-1, 2))
i = 0
for l in lines[1:]:
    d[i,:] = np.array([np.fromstring(l, dtype=float, sep=',')])
    i = i+1

Hier erzeugen wir uns einen 2-Dimensionalen Array mit den Grössen gegeben durch die Anzahl der Zeilen in der Datei und den Daten pro Zeile. Wir erzeugen das Array mit einer Zeile weniger als wir Zeilen in der Datei haben weil ja die erste Zeile der Datei keine Daten enthält.
Dann schreiben wir die Daten zeilenweise in das Array, dabei geben wir die Zeile i des Arrays explizit an. Der Doppelpunkt signalisiert, dass alle Elemente in dieser Zeile ersetzt werden sollen.

Nun können wir das Array ausgeben und überprüfen, dass es die Daten im richtigen Format enthält:

In [39]:
print(d)

[[0.1  0.31]
 [0.2  0.45]
 [0.3  0.55]]


In diesem Fall stehen die Werte der Unabhängigen Variable (x) in der ersten Spalte wobei die Werte der abhängigen Variable (y) in der zweiten Spalte stehen.
Es ist oft komfortabel die Daten aus dem 2-Dimensionalen Array in zwei 1-Dimensionale Arrays zu extrahieren:

In [40]:
x = d[:, 0]
y = d[:, 1]

print(x)
print(y)

[0.1 0.2 0.3]
[0.31 0.45 0.55]


Hier signalisiert der Doppelpunkt in der Klammer, dass alle Werte aus der ersten Dimension (der Spalte) übernommen werden sollen, die 1 bzw. 2 an der zweiten Stelle gibt die Spalte an, aus der wir die Daten extrahieren.

Nun können wir mit den Daten arbeiten, z.B. können wir den Wert einer weiteren Variable z=y^2 berechnen:

In [41]:
z = y**2

print(z)

[0.0961 0.2025 0.3025]


Wir können eine Datei auch zeilenweise schreiben:

In [42]:
with open('DataOut.txt', 'w') as f:
    f.writelines('x, y, z\n')
    for i in range(0, len(x)):
        f.writelines('{:0.5f}, {:0.5f}, {:0.5f}\n'.format(x[i], y[i], z[i]))

Dieses Beispiel ist sehr einfach gehalten. Wir verwenden wieder die 'with' Umgebung, um uns nicht weiter um das öffnen und schliessen der Datei kümmern zu müssen. Wir öffnen die Datei 'DataOut.txt' im Schreibmodus. Hier könnte auch wieder ein Pfad angegeben sein.
Mit der Zeile:<br>
`f.writelines('x, y, z\n')`<br>
schreiben wir den sogenannten Header in die Datei. Diese Zeile gibt an wie die einzelnen Spalten zu interpretieren sind.
Dann iterieren wir über die Länge der Arrays. In jeder Iteration erzeugen wir einen String aus den Werten der Arrays mit dem entsprechenden Index i: Die Ausdrücke in den geschweiften Klammern sind hierbei Platzhalter für die Parameter die in format() übergeben werden. In der geschweiften Klammer ist angegeben in welchem Format die Werte ausgegeben werden sollen, hier mit 5 Dezimalstellen (siehe https://pyformat.info für mehr Details). Das Ende der Zeilen wird mit dem '\n' Zeilenumbruch markiert. Je nach Betriebssystem können hier andere Steuerzeichen (oder deren Kombination) notwendig sein:<br>
\n Zeilenumbruch<br>
\r neue Zeile (Carriage Return)<br>
Eigentlich ist in Windows \r\n als Zeilenumbruch definiert, allerdings übersetzt Python \n (oder \r) automatisch in die entsprechende Kontrollsequenz des Betriebssystems. Es ist also aus Python heraus nicht notwendig auf diese Systemunterschiede zu achten.

Öffnen Sie wieder die so erzeugte Datei und inspizieren Sie das Ergebnis.

# **Skillcheck Aufgabe (Optional)**  
Diese Aufgabe ist eine fortgeschrittene Aufgabe, die alle vorgestellten Konzepte der Übung kombiniert. Zu dieser Aufgabe gibt es mehrere mögliche Lösungswege!  
Im aktuellen Ordner befindet sich die Datei Skillcheck.txt. Diese enthält eine Liste bestehend aus zwei verschiedenen Zahlen. Schreiben sie ein Programm, welches die Liste in ein Array lädt und dann durch diese in einem for loop iteriert. Am Ende soll die Zahl ausgegeben werden, die am häufigsten in der Datei vorkommt. (Unter der Annahme das die zwei Zahlen nicht gleich oft vorkommen).  
Extra Challenge: Schaffen sie es mit nur einer counter und einer candidate Variablen?

In [47]:
data = np.loadtxt('Skillcheck.txt')
num = 0
for i in data:
    if i == 1:
        num += 1
    elif i == 2:
        num -= 1

print(num)
if num > 0:
    print('one')
elif num < 0:
    print('two')

-110
two
